from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd
import os
import sys

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

print("=" * 50)
print("ML Backend API Starting...")
print(f"Available on: http://localhost:8000")
print(f"API Docs: http://localhost:8000/docs")
print("=" * 50)

@app.get("/api/experiments")
def get_experiments():
    try:
        # Load the CSV generated by evaluate.py
        csv_path = os.path.join(os.path.dirname(__file__), "..", "models", "comparison_results.csv")
        if not os.path.exists(csv_path):
            print(f"Warning: CSV not found at {csv_path}")
            return []
            
        df = pd.read_csv(csv_path).dropna(subset=["Algorithme"])
        
        # Transform the DataFrame to match the frontend expectations
        records = []
        for i, row in df.iterrows():
            algo_str = str(row["Algorithme"])
            record = {
                "id": f"exp-{i}",
                "timestamp": "2026-05-14T00:00:00Z", # Mock timestamp, we can parse it from run later
                "model": algo_str.lower().replace("+", "_").replace(" ", "_"),
                "modelName": algo_str,
                "version": "v1.0",
                "dataset": "churn_cleaned.csv",
                "datasetVersion": "v1",
                "accuracy": row.get("Accuracy", 0),
                "precision": row.get("Precision", 0),
                "recall": row.get("Recall", 0),
                "f1": row.get("F1-Score", 0),
                "auc": row.get("Accuracy", 0), # Mock AUC based on Accuracy for now
                "status": "success",
                "params": {"run": row["Run"], "details": row.get("Paramètres", "")},
                "notes": f"Run auto-logged from MLflow. Configuration: {row.get('Paramètres', '')}"
            }
            records.append(record)
        print(f"Loaded {len(records)} experiments from CSV")
        return records
    except Exception as e:
        print(f"Error loading experiments: {str(e)}")
        return []  # Return empty array instead of error object

@app.get("/api/status")
def get_status():
    return {"status": "ok", "message": "Backend ML API is running"}
